#!/usr/bin/env node
/**
 * Structural checks the type system cannot make.
 *
 * Every one of these was a real defect found by review, not a hypothetical:
 * doors landing you inside furniture, props advertised by a zone with no
 * hotspot to reach them, and a location you can walk into but not out of.
 */
import { readFile, readdir } from 'node:fs/promises';

const src = async (p) => readFile(p, 'utf8');

/**
 * Blockers are mostly literals but some are generated by
 * `...[a, b].map((x) => [x, z, hw, hd])`. Expand those, and never mistake the
 * source list for a blocker — reading `[-10, -3, 4, 10]` (four lamp x
 * positions) as a rectangle produced a phantom collider that failed the spawn.
 */
function parseBlockers(text) {
  const out = [];
  const mapped = /\.\.\.\[([^\]]*)\]\.map\(\([^)]*\)\s*=>\s*\[\s*\w+\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)/g;
  let stripped = text;
  for (const m of text.matchAll(mapped)) {
    for (const v of m[1].split(',')) {
      const n = Number(v.trim());
      if (!Number.isNaN(n)) out.push([n, Number(m[2]), Number(m[3]), Number(m[4])]);
    }
    stripped = stripped.replace(m[0], '');
  }
  // Anything still spread from a named collection cannot be resolved here.
  stripped = stripped.replace(/\.\.\.[A-Z_]+\.map\([\s\S]*?\)/g, '');
  for (const m of stripped.matchAll(/\[\s*(-?[\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+)\s*\]/g)) {
    out.push(m.slice(1, 5).map(Number));
  }
  return out;
}

// Parse the specs out of the location modules rather than importing TSX.
const files = ['room', 'city', 'gym', 'tower', 'server'];
const specs = {};
for (const f of files) {
  const text = await src(`src/world/locations/${f}.tsx`);
  const grab = (key) => {
    const m = text.match(new RegExp(`^  ${key}: (\\[[\\s\\S]*?\\]|[^,\\n]+),$`, 'm'));
    return m ? m[1] : null;
  };
  // Bracket-matched, not regex-terminated: the first version only handled
  // multi-line arrays and silently returned '' for single-line ones, which
  // made real doors and hotspots look missing.
  const arr = (key) => {
    const start = text.indexOf(`\n  ${key}: [`);
    if (start === -1) return '';
    let i = text.indexOf('[', start);
    let depth = 0;
    for (let j = i; j < text.length; j++) {
      if (text[j] === '[') depth++;
      else if (text[j] === ']') {
        depth--;
        if (depth === 0) return text.slice(i + 1, j);
      }
    }
    return '';
  };
  specs[f] = {
    bounds: JSON.parse(grab('bounds') ?? '[]'),
    spawn: JSON.parse(grab('spawn') ?? '[]'),
    blockers: parseBlockers(arr('blockers')),
    doors: [...arr('doors').matchAll(/to:\s*'(\w+)'[\s\S]*?arriveAt:\s*\[\s*(-?[\d.]+),\s*(-?[\d.]+)\s*\]/g)].map(
      (m) => ({ to: m[1], arriveAt: [Number(m[2]), Number(m[3])] }),
    ),
    hotspots: [...arr('hotspots').matchAll(/prop:\s*'([\w-]+)'/g)].map((m) => m[1]),
  };
}

const fails = [];
const R = 0.3;

for (const [id, s] of Object.entries(specs)) {
  const inBounds = ([x, z], where) => {
    const [x0, x1, z0, z1] = s.bounds;
    if (x < x0 + R || x > x1 - R || z < z0 + R || z > z1 - R) {
      fails.push(`${where} lands (${x}, ${z}) outside ${id}'s walkable bounds ${JSON.stringify(s.bounds)}`);
    }
  };
  const notInBlocker = ([x, z], where) => {
    for (const [bx, bz, hw, hd] of s.blockers) {
      if (Math.abs(x - bx) < hw + R && Math.abs(z - bz) < hd + R) {
        fails.push(`${where} lands (${x}, ${z}) inside a blocker of ${id} at (${bx}, ${bz})`);
      }
    }
  };
  inBounds(s.spawn, `${id} spawn`);
  notInBlocker(s.spawn, `${id} spawn`);
}

// Every door's arriveAt is a coordinate in the DESTINATION.
for (const [id, s] of Object.entries(specs)) {
  for (const d of s.doors) {
    const dest = specs[d.to];
    if (!dest) {
      fails.push(`${id} has a door to "${d.to}", which is not a location`);
      continue;
    }
    const [x, z] = d.arriveAt;
    const [x0, x1, z0, z1] = dest.bounds;
    if (x < x0 + R || x > x1 - R || z < z0 + R || z > z1 - R) {
      fails.push(`${id} -> ${d.to} arrives at (${x}, ${z}), outside ${d.to}'s bounds ${JSON.stringify(dest.bounds)}`);
    }
    for (const [bx, bz, hw, hd] of dest.blockers) {
      if (Math.abs(x - bx) < hw + R && Math.abs(z - bz) < hd + R) {
        fails.push(`${id} -> ${d.to} arrives at (${x}, ${z}), inside a blocker at (${bx}, ${bz})`);
      }
    }
    if (!dest.doors.some((back) => back.to === id)) {
      fails.push(`${id} -> ${d.to} is one-way: ${d.to} has no door back to ${id}`);
    }
  }
}

// Every prop a zone advertises must have a hotspot, or a post attached to it
// is unreachable in the world with nothing to say so.
const consts = await src('src/consts.ts');
for (const block of consts.matchAll(/id: '(\w+)',[\s\S]*?props: \[([^\]]*)\]/g)) {
  const zone = block[1];
  if (zone === 'tv') continue;
  const declared = [...block[2].matchAll(/'([\w-]+)'/g)].map((m) => m[1]);
  const reachable = specs[zone]?.hotspots ?? [];
  for (const prop of declared) {
    if (!reachable.includes(prop)) {
      fails.push(`zone "${zone}" advertises prop "${prop}" with no hotspot — a post on it is unreachable in 3D`);
    }
  }
}

// Every post's zone+prop must be reachable.
for (const file of await readdir('src/content/blog')) {
  if (!file.endsWith('.md')) continue;
  const text = await src(`src/content/blog/${file}`);
  const zone = text.match(/^zone:\s*(\S+)/m)?.[1];
  const prop = text.match(/^prop:\s*(\S+)/m)?.[1];
  if (!zone || !prop || zone === 'tv') continue;
  if (!(specs[zone]?.hotspots ?? []).includes(prop)) {
    fails.push(`${file}: zone "${zone}" prop "${prop}" has no hotspot — this post cannot be found in the world`);
  }
}

if (fails.length) {
  console.error('\n  WORLD STRUCTURE\n');
  for (const f of fails) console.error(`  ✗ ${f}`);
  console.error('');
  process.exit(1);
}
console.log(`\n  ✓ world structure: ${Object.keys(specs).length} locations, all doors two-way and landing on walkable floor\n`);
